import Navbar from './Navbar'
import './globals.css'
import { JetBrains_Mono, Noto_Sans, Noto_Sans_KR } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const jetbrains_mono = JetBrains_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: "--font-jetbrains_mono"
});

const noto_sans_kr = Noto_Sans_KR({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-noto_sans_kr"
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${noto_sans_kr.className}`}>
        {/* <Navbar/> */}
        {children}
        </body>
    </html>
  )
}
